---
- name: Pull new Docker images
  community.docker.docker_compose:
    project_src: "/home/{{ ansible_user }}/docker-rasenmaeher-integration"
    files:
      - docker-compose.yml
    pull: yes
    state: present

- name: Redeploy Docker Compose project
  community.docker.docker_compose:
    project_src: "/home/{{ ansible_user }}/docker-rasenmaeher-integration"
    files:
      - docker-compose.yml
    state: present
    recreate: smart
    remove_orphans: true
    remove_volumes: false  # Ensures that volumes are not removed
