---
- name: Localhost | Prepare local playbook to manage the server | Check if there are ansible keys preseent
  stat:
    path: "{{ ansible_ssh_private_key_file }}"
  register: ansibleuserkey_preserence

- name: Localhost | Prepare local playbook to manage the server | Create target Ansible user ssh pair
  community.crypto.openssh_keypair:
    state: present
    path: "{{ ansible_ssh_private_key_file }}"
    #passphrase: '{{ lxc_ansibleuser_sshpass }}'
    type: rsa
    size: 2048
    comment: "{{ ansible_user }}@{{ server_domain }}"
  when: not ansibleuserkey_preserence.stat.exists

#- name: Make sure .ssh directory permissions are all right
#  become: yes
#  file:
#    path: '{{ ssh_folder }}'
#    mode: 700
