---
- name: Push target Ansible user to the target, at first contact
  delegate_to: localhost
  shell: |
    ssh-copy-id -i {{ ansible_ssh_public_key_file }} {{ target_ansible_user }}@{{ target_address }}
