---
- name: Prepare VM | Ensure passwordless sudo is enabled for ansibleuser
  become: true
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^{{ lxc_ansibleuser }}\s+ALL=(ALL)\s+NOPASSWD:\s+ALL$'
    line: '{{ lxc_ansibleuser }} ALL=(ALL) NOPASSWD: ALL'
  when: lxc_ansibleuser != 'root'
  tags: ['sudo_passwordless']
