---
- name: Environment | Prepare VM/LXC SSH connections | Check if ssh was installed
  apt:
    pkg: openssh-server
    state: latest
    update_cache: true
    cache_valid_time: 3600
  notify: restart ssh

- name: Proxmox | Setup PVE root ssh credentials | Reload sshd.service, if changes made
  meta: flush_handlers