---
- name: Prepare VM | Prepare ssh | Check if ssh was installed
  apt:
    pkg: openssh-server
    state: latest
    update_cache: true
    cache_valid_time: 3600
  notify: restart ssh

- name: Prepare VM | Prepare ssh | Reload sshd.service, if changes made
  meta: flush_handlers