---
### RM Secrets
### Set these as .env variables.
keycloak_db_password: "{{ lookup('env', 'KEYCLOAK_DATABASE_PASSWORD', default='') }}"
rasenmaeher_db_password: "{{ lookup('env', 'RM_DATABASE_PASSWORD', default='') }}"
tak_db_password: "{{ lookup('env', 'TAK_DATABASE_PASSWORD', default='') }}"
postgres_password: "{{ lookup('env', 'POSTGRES_PASSWORD', default='') }}" 
ldap_admin_password: "{{ lookup('env', 'LDAP_ADMIN_PASSWORD', default='') }}"
keycloak_admin_password: "{{ lookup('env', 'KEYCLOAK_ADMIN_PASSWORD', default='') }}"
keycloak_management_password: "{{ lookup('env', 'KEYCLOAK_MANAGEMENT_PASSWORD', default='') }}"
cfssl_ca_name: "{{ lookup('env', 'CFSSL_CA_NAME', default='') }}"
takserver_cert_pass: "{{ lookup('env', 'TAKSERVER_CERT_PASS', default='') }}"
tak_ca_pass: "{{ lookup('env', 'TAK_CA_PASS', default='') }}"
