### to-do link VM preparation playbook
- name: VM Playbook | Prepare target VM
  gather_facts: yes
  hosts: all
  become: true

  roles:
    - prepare-vm
    - geerlingguy.docker
    - role: dy-ddns-cron-job
      when: use_ddns | default(false) | bool
    - role: dy-ddns-hello
      when: use_ddns_one_time | default(false) | bool
