---
- name: Prepare VM | Ensure passwordless sudo is enabled for ansibleuser
  become: true
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^{{ ansible_user }}\s+ALL=(ALL)\s+NOPASSWD:\s+ALL$' ## pragma: allowlist secret
    line: "{{ ansible_user }} ALL=(ALL) NOPASSWD: ALL" ## pragma: allowlist secret
  when: ansible_user != 'root' ## pragma: allowlist secret
  tags: ["sudo_passwordless"]
