---
- name: Prepare VM | Ensure passwordless sudo is enabled for ansibleuser
  become: true
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^{{ ansible_user }}\s+ALL=(ALL)\s+NOPASSWD:\s+ALL$'
    line: '{{ ansible_user }} ALL=(ALL) NOPASSWD: ALL'
  when: ansible_user != 'root'
  tags: ['sudo_passwordless']
