---
- name: Manage RM Deployment
  hosts: all
  gather_facts: yes

  tasks:
    - name: Remove a RM deployment
      include_role:
        name: ./playbooks/roles/rm-remove
      when: remove_composition | default(false) | bool

    - name: Add new admin login code to RM
      include_role:
        name: ./playbooks/roles/rm-add-admin
      when: add_admin | default(false) | bool

    - name: Pull new version and redeploy RM
      include_role:
        name: ./playbooks/roles/rm-pull-new
      when: pull_new | default(false) | bool
