---
- name: Prepare to deploy RM | Generate random secrets if not defined
  set_fact:
    keycloak_db_password: "{{ keycloak_db_password | length > 0 | ternary(keycloak_db_password, lookup('community.general.random_string')) }}"
    rasenmaeher_db_password: "{{ rasenmaeher_db_password | length > 0 | ternary(rasenmaeher_db_password, lookup('community.general.random_string')) }}"
    tak_db_password: "{{ tak_db_password | length > 0 | ternary(tak_db_password, lookup('community.general.random_string')) }}"
    postgres_password: "{{ postgres_password | length > 0 | ternary(postgres_password, lookup('community.general.random_string')) }}"
    ldap_admin_password: "{{ ldap_admin_password | length > 0 | ternary(ldap_admin_password, lookup('community.general.random_string')) }}"
    keycloak_admin_password: "{{ keycloak_admin_password | length > 0 | ternary(keycloak_admin_password, lookup('community.general.random_string')) }}"
    keycloak_management_password: "{{ keycloak_management_password | length > 0 | ternary(keycloak_management_password, lookup('community.general.random_string')) }}"
    cfssl_ca_name: "{{ cfssl_ca_name | length > 0 | ternary(cfssl_ca_name, 'CA_' + lookup('community.general.random_string')) }}"
    takserver_cert_pass: "{{ takserver_cert_pass | length > 0 | ternary(takserver_cert_pass, lookup('community.general.random_string')) }}"
    tak_ca_pass: "{{ tak_ca_pass | length > 0 | ternary(tak_ca_pass, lookup('community.general.random_string')) }}"

- name: Prepare to deploy RM | Generate environment file with random passwords
  template:
    src: "templates/env.j2"
    dest: "../.env"
  vars:
    env_content: |
      KEYCLOAK_DATABASE_PASSWORD={{ keycloak_db_password }}
      RM_DATABASE_PASSWORD={{ rasenmaeher_db_password }}
      TAK_DATABASE_PASSWORD={{ tak_db_password }}
      POSTGRES_PASSWORD={{ postgres_password }}
      LDAP_ADMIN_PASSWORD={{ ldap_admin_password }}
      KEYCLOAK_ADMIN_PASSWORD={{ keycloak_admin_password }}
      KEYCLOAK_MANAGEMENT_PASSWORD={{ keycloak_management_password }}
      CFSSL_CA_NAME={{ cfssl_ca_name }}
      TAKSERVER_CERT_PASS={{ takserver_cert_pass }}
      TAK_CA_PASS={{ tak_ca_pass }}
