---
- name: Load vars from role if not already set
  include_vars:
    file: "../vars/vars.yml"

- name: Generate random secrets if empty, avoiding specific characters
  set_fact:
    "{{ item.key }}": "{{ lookup('community.general.random_string', length=16, special=false) }}"
  loop: "{{ secrets | dict2items }}"
  when: item.value | trim == '' or item.value is none
  delegate_to: localhost

- name: Ensure the directory for host-specific secrets exists on the control node
  ansible.builtin.file:
    path: "../inventory/host_vars/{{ inventory_hostname }}/"
    state: directory
    mode: '0755'
  delegate_to: localhost  # Executes this task on the control node

- name: Write secrets to file on the control node
  copy:
    content: |
      keycloak_db_password: "{{ keycloak_db_password }}"
      rasenmaeher_db_password: "{{ rasenmaeher_db_password }}"
      tak_db_password: "{{ tak_db_password }}"
      postgres_password: "{{ postgres_password }}"
      ldap_admin_password: "{{ ldap_admin_password }}"
      keycloak_admin_password: "{{ keycloak_admin_password }}"
      keycloak_management_password: "{{ keycloak_management_password }}"
      cfssl_ca_name: "{{ cfssl_ca_name }}"
      takserver_cert_pass: "{{ takserver_cert_pass }}"
      tak_ca_pass: "{{ tak_ca_pass }}"
    dest: "../inventory/host_vars/{{ inventory_hostname }}/rasenmaeher_secrets.yml"
    mode: '0644'
  delegate_to: localhost

- name: debugg
  ansible.builtin.command:
    cmd: "ls ../"
  delegate_to: localhost

- name: Encrypt secrets file with Ansible Vault on the control node
  become: yes
  ansible.builtin.command:
    cmd: "ansible-vault encrypt '../inventory/host_vars/{{ inventory_hostname }}/rasenmaeher_secrets.yml' --vault-password-file ../vault_pass.txt"
  delegate_to: localhost 
  when: ansible_vault_password is defined
  register: vault_encryption_result
  ignore_errors: true  # Optionally add this to not fail the playbook and examine the output

- name: Debug vault encryption result
  ansible.builtin.debug:
    var: vault_encryption_result
  when: vault_encryption_result is defined
